version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./config/development.env
  frontend:
    image: "notes-frontend-dev"
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
  backend:
    image: "notes-backend-dev"
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7100:7100"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    env_file:
      - ./config/development.env
volumes:
  mongo-data: